name: khbr_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation,
  # File Downloading, Timeout etc.
  dio: ^3.0.10
  # Flutter plugin for reading and writing
  shared_preferences: ^0.5.10
  # Flutter widgets that make it easy to implement the BLoC design pattern.
  flutter_bloc: ^6.0.1
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation
  # and to access the concrete implementation from everywhere in your App
  get_it: ^4.0.4
  # The Font Awesome Icon pack
  font_awesome_flutter: ^8.5.0
  fluttertoast: ^7.0.2
  http: ^0.12.2
  typicons_flutter: ^0.4.2
  url_launcher: ^5.5.3
  rflutter_alert: ^1.0.3
  lite_rolling_switch: ^0.1.1

  provider: ^4.3.2+2
  multiple_select: ^0.1.23
  share: ^0.6.5+2
  flutter_plugin_pdf_viewer: ^1.0.7
  splashscreen: ^1.2.0
  flutter_tts: ^1.3.0
  multiselect_formfield: ^0.1.5
  pagination_view: ^1.0.3+2
dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  # Automatically generate code for converting to and from JSON by Dart classes.
  json_serializable: ^3.2.3

  # Tools to write binaries that run builders.
  build_runner: ^1.7.2
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/khbar.png
    - assets/images/khbaroff.png
    - assets/pdf/test.pdf
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Arslan
      fonts:
        - asset: assets/fonts/arslan.ttf
    - family: Jazeera
      fonts:
        - asset: assets/fonts/Jazeera.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar.ttf